# Quantitative Momentum

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import yfinance as yf
import datetime as dt
import math

from jupyterthemes import jtplot
jtplot.style(theme='onedork', figsize=(15, 9))

In [4]:
hqm_mom = pd.read_csv('../data/strategy/hqm_momentum.csv', index_col=0)
hqm_mom

,Ticker,Price,Number of Shares to Buy,One-Year Price Return,One-Year Return Percentile,Six-Month Price Return,Six-Month Return Percentile,Three-Month Price Return,Three-Month Return Percentile,One-Month Price Return,One-Month Return Percentile,HQM Scores
0,A,140.19,NaN,0.116108,NaN,0.077113,NaN,-0.096407,NaN,0.054350,NaN,NaN
1,AAL,13.10,NaN,-0.310526,NaN,-0.007576,NaN,-0.233021,NaN,-0.062947,NaN,NaN
2,AAP,126.87,NaN,-0.395825,NaN,-0.235751,NaN,-0.139079,NaN,0.075862,NaN,NaN
3,AAPL,165.23,NaN,0.006962,NaN,0.165410,NaN,0.217318,NaN,0.066000,NaN,NaN
4,ABBV,161.18,NaN,0.031554,NaN,0.137103,NaN,0.064338,NaN,0.054745,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
496,YUM,137.10,NaN,0.131085,NaN,0.252303,NaN,0.051945,NaN,0.080804,NaN,NaN
497,ZBH,133.46,NaN,0.068028,NaN,0.212273,NaN,0.087023,NaN,0.075655,NaN,NaN
498,ZBRA,300.46,NaN,-0.236791,NaN,0.148372,NaN,0.023435,NaN,0.040698,NaN,NaN
499,ZION,30.93,NaN,-0.493531,NaN,-0.394247,NaN,-0.387094,NaN,0.033066,NaN,NaN
500,ZTS,174.62,NaN,-0.060161,NaN,0.170988,NaN,0.096888,NaN,0.061713,NaN,NaN